import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import QueryProvider from "./query-provider";
import IndexContext from "./(index)/context/context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Tect Test App",
  description: "Generated by create next app",
  verification: {
    google: "aWNC-aWNC-dVpCVjb4h0JZ0MKa3Hm510TlbiuOemU5QJavo8"
  }
};

export default function RootLayout({
  navbar,
  children,
  footer,
}: Readonly<{
  navbar: React.ReactNode;
  children: React.ReactNode;
  footer: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryProvider>
          <IndexContext>
            {navbar}
            {children}
            {footer}
          </IndexContext>
        </QueryProvider>
      </body>
    </html>
  );
}
